class KeyCode():
    code: int = None

    def __init__(self, code: int):
        self.code = code

    def __eq__(self, other):
            if self.ft==other.ft and self.inch==other.inch:
                return "both objects are equal"
            else:
                return "both objects are not equal"

KEY_LBUTTON = KeyCode(0x01)
KEY_RBUTTON = KeyCode(0x02)
KEY_CANCEL = KeyCode(0x03)
KEY_MBUTTON = KeyCode(0x04)

KEY_XBUTTON1 = KeyCode(0x05)
KEY_XBUTTON2 = KeyCode(0x06)

KEY_BACK = KeyCode(0x08)
KEY_TAB = KeyCode(0x09)

KEY_CLEAR = KeyCode(0x0C)
KEY_RETURN = KeyCode(0x0D)

KEY_SHIFT = KeyCode(0x10)
KEY_CONTROL = KeyCode(0x11)
KEY_MENU = KeyCode(0x12)
KEY_PAUSE = KeyCode(0x13)
KEY_CAPITAL = KeyCode(0x14)

KEY_KANA = KeyCode(0x15)
KEY_HANGEUL = KeyCode(0x15)
KEY_HANGUL = KeyCode(0x15)

KEY_JUNJA = KeyCode(0x17)
KEY_FINAL = KeyCode(0x18)
KEY_HANJA = KeyCode(0x19)
KEY_KANJI = KeyCode(0x19)

KEY_ESCAPE = KeyCode(0x1B)

KEY_CONVERT = KeyCode(0x1C)
KEY_NONCONVERT = KeyCode(0x1D)
KEY_ACCEPT = KeyCode(0x1E)
KEY_MODECHANGE = KeyCode(0x1F)

KEY_SPACE = KeyCode(0x20)
KEY_PRIOR = KeyCode(0x21)
KEY_NEXT = KeyCode(0x22)
KEY_END = KeyCode(0x23)
KEY_HOME = KeyCode(0x24)
KEY_LEFT = KeyCode(0x25)
KEY_UP = KeyCode(0x26)
KEY_RIGHT = KeyCode(0x27)
KEY_DOWN = KeyCode(0x28)
KEY_SELECT = KeyCode(0x29)
KEY_PRINT = KeyCode(0x2A)
KEY_EXECUTE = KeyCode(0x2B)
KEY_SNAPSHOT = KeyCode(0x2C)
KEY_INSERT = KeyCode(0x2D)
KEY_DELETE = KeyCode(0x2E)
KEY_HELP = KeyCode(0x2F)

KEY_0 = KeyCode(0x30)
KEY_1 = KeyCode(0x31)
KEY_2 = KeyCode(0x32)
KEY_3 = KeyCode(0x33)
KEY_4 = KeyCode(0x34)
KEY_5 = KeyCode(0x35)
KEY_6 = KeyCode(0x36)
KEY_7 = KeyCode(0x37)
KEY_8 = KeyCode(0x38)
KEY_9 = KeyCode(0x39)

KEY_A = KeyCode(0x41)
KEY_B = KeyCode(0x42)
KEY_C = KeyCode(0x43)
KEY_D = KeyCode(0x44)
KEY_E = KeyCode(0x45)
KEY_F = KeyCode(0x46)
KEY_G = KeyCode(0x47)
KEY_H = KeyCode(0x48)
KEY_I = KeyCode(0x49)
KEY_J = KeyCode(0x4A)
KEY_K = KeyCode(0x4B)
KEY_L = KeyCode(0x4C)
KEY_M = KeyCode(0x4D)
KEY_N = KeyCode(0x4E)
KEY_O = KeyCode(0x4F)
KEY_P = KeyCode(0x50)
KEY_Q = KeyCode(0x51)
KEY_R = KeyCode(0x52)
KEY_S = KeyCode(0x53)
KEY_T = KeyCode(0x54)
KEY_U = KeyCode(0x55)
KEY_V = KeyCode(0x56)
KEY_W = KeyCode(0x57)
KEY_X = KeyCode(0x58)
KEY_Y = KeyCode(0x59)
KEY_Z = KeyCode(0x5A)

KEY_LWIN = KeyCode(0x5B)
KEY_RWIN = KeyCode(0x5C)
KEY_APPS = KeyCode(0x5D)

KEY_SLEEP = KeyCode(0x5F)

KEY_NUMPAD0 = KeyCode(0x60)
KEY_NUMPAD1 = KeyCode(0x61)
KEY_NUMPAD2 = KeyCode(0x62)
KEY_NUMPAD3 = KeyCode(0x63)
KEY_NUMPAD4 = KeyCode(0x64)
KEY_NUMPAD5 = KeyCode(0x65)
KEY_NUMPAD6 = KeyCode(0x66)
KEY_NUMPAD7 = KeyCode(0x67)
KEY_NUMPAD8 = KeyCode(0x68)
KEY_NUMPAD9 = KeyCode(0x69)
KEY_MULTIPLY = KeyCode(0x6A)
KEY_ADD = KeyCode(0x6B)
KEY_SEPARATOR = KeyCode(0x6C)
KEY_SUBTRACT = KeyCode(0x6D)
KEY_DECIMAL = KeyCode(0x6E)
KEY_DIVIDE = KeyCode(0x6F)
KEY_F1 = KeyCode(0x70)
KEY_F2 = KeyCode(0x71)
KEY_F3 = KeyCode(0x72)
KEY_F4 = KeyCode(0x73)
KEY_F5 = KeyCode(0x74)
KEY_F6 = KeyCode(0x75)
KEY_F7 = KeyCode(0x76)
KEY_F8 = KeyCode(0x77)
KEY_F9 = KeyCode(0x78)
KEY_F10 = KeyCode(0x79)
KEY_F11 = KeyCode(0x7A)
KEY_F12 = KeyCode(0x7B)
KEY_F13 = KeyCode(0x7C)
KEY_F14 = KeyCode(0x7D)
KEY_F15 = KeyCode(0x7E)
KEY_F16 = KeyCode(0x7F)
KEY_F17 = KeyCode(0x80)
KEY_F18 = KeyCode(0x81)
KEY_F19 = KeyCode(0x82)
KEY_F20 = KeyCode(0x83)
KEY_F21 = KeyCode(0x84)
KEY_F22 = KeyCode(0x85)
KEY_F23 = KeyCode(0x86)
KEY_F24 = KeyCode(0x87)

KEY_NAVIGATION_VIEW = KeyCode(0x88)
KEY_NAVIGATION_MENU = KeyCode(0x89)
KEY_NAVIGATION_UP = KeyCode(0x8A)
KEY_NAVIGATION_DOWN = KeyCode(0x8B)
KEY_NAVIGATION_LEFT = KeyCode(0x8C)
KEY_NAVIGATION_RIGHT = KeyCode(0x8D)
KEY_NAVIGATION_ACCEPT = KeyCode(0x8E)
KEY_NAVIGATION_CANCEL = KeyCode(0x8F)

KEY_NUMLOCK = KeyCode(0x90)
KEY_SCROLL = KeyCode(0x91)

KEY_OEM_NEC_EQUAL = KeyCode(0x92)

KEY_OEM_FJ_JISHO = KeyCode(0x92)
KEY_OEM_FJ_MASSHOU = KeyCode(0x93)
KEY_OEM_FJ_TOUROKU = KeyCode(0x94)
KEY_OEM_FJ_LOYA = KeyCode(0x95)
KEY_OEM_FJ_ROYA = KeyCode(0x96)

KEY_LSHIFT = KeyCode(0xA0)
KEY_RSHIFT = KeyCode(0xA1)
KEY_LCONTROL = KeyCode(0xA2)
KEY_RCONTROL = KeyCode(0xA3)
KEY_LMENU = KeyCode(0xA4)
KEY_RMENU = KeyCode(0xA5)

KEY_BROWSER_BACK = KeyCode(0xA6)
KEY_BROWSER_FORWARD = KeyCode(0xA7)
KEY_BROWSER_REFRESH = KeyCode(0xA8)
KEY_BROWSER_STOP = KeyCode(0xA9)
KEY_BROWSER_SEARCH = KeyCode(0xAA)
KEY_BROWSER_FAVORITES = KeyCode(0xAB)
KEY_BROWSER_HOME = KeyCode(0xAC)

KEY_VOLUME_MUTE = KeyCode(0xAD)
KEY_VOLUME_DOWN = KeyCode(0xAE)
KEY_VOLUME_UP = KeyCode(0xAF)
KEY_MEDIA_NEXT_TRACK = KeyCode(0xB0)
KEY_MEDIA_PREV_TRACK = KeyCode(0xB1)
KEY_MEDIA_STOP = KeyCode(0xB2)
KEY_MEDIA_PLAY_PAUSE = KeyCode(0xB3)
KEY_LAUNCH_MAIL = KeyCode(0xB4)
KEY_LAUNCH_MEDIA_SELECT = KeyCode(0xB5)
KEY_LAUNCH_APP1 = KeyCode(0xB6)
KEY_LAUNCH_APP2 = KeyCode(0xB7)

KEY_OEM_1 = KeyCode(0xBA)
KEY_OEM_PLUS = KeyCode(0xBB)
KEY_OEM_COMMA = KeyCode(0xBC)
KEY_OEM_MINUS = KeyCode(0xBD)
KEY_OEM_PERIOD = KeyCode(0xBE)
KEY_OEM_2 = KeyCode(0xBF)
KEY_OEM_3 = KeyCode(0xC0)

KEY_GAMEPAD_A = KeyCode(0xC3)
KEY_GAMEPAD_B = KeyCode(0xC4)
KEY_GAMEPAD_X = KeyCode(0xC5)
KEY_GAMEPAD_Y = KeyCode(0xC6)
KEY_GAMEPAD_RIGHT_SHOULDER = KeyCode(0xC7)
KEY_GAMEPAD_LEFT_SHOULDER = KeyCode(0xC8)
KEY_GAMEPAD_LEFT_TRIGGER = KeyCode(0xC9)
KEY_GAMEPAD_RIGHT_TRIGGER = KeyCode(0xCA)
KEY_GAMEPAD_DPAD_UP = KeyCode(0xCB)
KEY_GAMEPAD_DPAD_DOWN = KeyCode(0xCC)
KEY_GAMEPAD_DPAD_LEFT = KeyCode(0xCD)
KEY_GAMEPAD_DPAD_RIGHT = KeyCode(0xCE)
KEY_GAMEPAD_MENU = KeyCode(0xCF)
KEY_GAMEPAD_VIEW = KeyCode(0xD0)
KEY_GAMEPAD_LEFT_THUMBSTICK_BUTTON = KeyCode(0xD1)
KEY_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = KeyCode(0xD2)
KEY_GAMEPAD_LEFT_THUMBSTICK_UP = KeyCode(0xD3)
KEY_GAMEPAD_LEFT_THUMBSTICK_DOWN = KeyCode(0xD4)
KEY_GAMEPAD_LEFT_THUMBSTICK_RIGHT = KeyCode(0xD5)
KEY_GAMEPAD_LEFT_THUMBSTICK_LEFT = KeyCode(0xD6)
KEY_GAMEPAD_RIGHT_THUMBSTICK_UP = KeyCode(0xD7)
KEY_GAMEPAD_RIGHT_THUMBSTICK_DOWN = KeyCode(0xD8)
KEY_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = KeyCode(0xD9)
KEY_GAMEPAD_RIGHT_THUMBSTICK_LEFT = KeyCode(0xDA)

KEY_OEM_4 = KeyCode(0xDB)
KEY_OEM_5 = KeyCode(0xDC)
KEY_OEM_6 = KeyCode(0xDD)
KEY_OEM_7 = KeyCode(0xDE)
KEY_OEM_8 = KeyCode(0xDF)

KEY_OEM_AX = KeyCode(0xE1)
KEY_OEM_102 = KeyCode(0xE2)
KEY_ICO_HELP = KeyCode(0xE3)
KEY_ICO_00 = KeyCode(0xE4)
KEY_PROCESSKEY = KeyCode(0xE5)
KEY_ICO_CLEAR = KeyCode(0xE6)
KEY_PACKET = KeyCode(0xE7)

KEY_OEM_RESET = KeyCode(0xE9)
KEY_OEM_JUMP = KeyCode(0xEA)
KEY_OEM_PA1 = KeyCode(0xEB)
KEY_OEM_PA2 = KeyCode(0xEC)
KEY_OEM_PA3 = KeyCode(0xED)
KEY_OEM_WSCTRL = KeyCode(0xEE)
KEY_OEM_CUSEL = KeyCode(0xEF)
KEY_OEM_ATTN = KeyCode(0xF0)
KEY_OEM_FINISH = KeyCode(0xF1)
KEY_OEM_COPY = KeyCode(0xF2)
KEY_OEM_AUTO = KeyCode(0xF3)
KEY_OEM_ENLW = KeyCode(0xF4)
KEY_OEM_BACKTAB = KeyCode(0xF5)

KEY_ATTN = KeyCode(0xF6)
KEY_CRSEL = KeyCode(0xF7)
KEY_EXSEL = KeyCode(0xF8)
KEY_EREOF = KeyCode(0xF9)
KEY_PLAY = KeyCode(0xFA)
KEY_ZOOM = KeyCode(0xFB)
KEY_NONAME = KeyCode(0xFC)
KEY_PA1 = KeyCode(0xFD)
KEY_OEM_CLEAR = KeyCode(0xFE)


key_code_names = [name for name, value in locals().items() if name.startswith('KEY_')]

key_code_to_names = {value.code : value for name, value in locals().items() if name.startswith('KEY_')}

def get_key_code(code: int) -> KeyCode:
     if not code in key_code_to_names:
        return None
     
     return key_code_to_names[code]